### ISSUE TITLE
BNL multi-pi distributions

### ISSUE THREAD

**Issue by clarenc3** [NUISANCEMC/nuisance#26]
BNL have some neat multi-pi distributions to complement ANL.

https://journals.aps.org/prd/abstract/10.1103/PhysRevD.34.2554

Section IV

"Charged-current exclusive pion production in neutrino-deuterium interactions", T. Kitagaki et al
Physical Review D, Volume 34, Number 9, 1 November 1986

**Comment by wilkinson-nu** [comment]
Figures 17a and 17b are now in. 
Figures 18a and 18b are now digitized, but each event can add multiple entries to the plot so needs some attention.
The 2, 3, and 4 pi XSECs from Figure 19 are in, but the 5 pi XSEC is unreadable.
Figures 21 and 22 are digitized, but not yet added

**Comment by clarenc3** [comment]
Closing because resolved with https://github.com/NUISANCEMC/nuisance/commit/23d8aa55d44592281281aeb9086fc4b56d439d43 and associated commits.
