### ISSUE TITLE
BNL mass distributions

### ISSUE THREAD

**Issue by clarenc3** [NUISANCEMC/nuisance#27]
https://journals.aps.org/prd/abstract/10.1103/PhysRevD.34.2554

(ANL) and BNL have some nice M(pi+mu), M(pi+prot) etc distributions that haven't made it in to NUISANCE. 

e.g. figure 4, figure 5, figure 6, figure 8 (very cool)

**Comment by wilkinson-nu** [comment]
Figures 4, 5 and 6 are now in, with sample names:
BNL_CC1ppip_Evt_1DWNpi_nu
BNL_CC1ppip_Evt_1DWNmu_nu
BNL_CC1ppip_Evt_1DWmupi_nu
BNL_CC1npip_Evt_1DWNpi_nu
BNL_CC1npip_Evt_1DWNmu_nu
BNL_CC1npip_Evt_1DWmupi_nu
BNL_CC1pi0_Evt_1DWNpi_nu
BNL_CC1pi0_Evt_1DWNmu_nu
BNL_CC1pi0_Evt_1DWmupi_nu

**Comment by clarenc3** [comment]
Closing because resolved with https://github.com/NUISANCEMC/nuisance/commit/196b449bbff6b9e78be24863ecbe085b50dc0ce6
