### ISSUE TITLE
Can't find the MINERvA CVMFS area in CVMFS

### ISSUE THREAD

**Issue by zzj1965186613** [NUISANCEMC/nuisance#63]
I want to use nuisance via CVMFS private mount, but I can't find the MINERvA CVMFS area.Can you tell me the correct configuration of url, keys, proxy, etc. in the .conf file?

**Comment by luketpickering** [comment]
Sorry, this is really not a NUISANCE issue, or appropriate for an issue on the github, feel free to ask on slack.
